<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[testing has begun  a]]>
    </line>
    <line>
      <![CDATA[test a running ]]>
    </line>
    <line>
      <![CDATA[test run ofa successful]]>
    </line>
    <line>
      <![CDATA[testing has begun  c]]>
    </line>
    <line>
      <![CDATA[assertion provoded as fail  c]]>
    </line>
    <line>
      <![CDATA[testing has begun  b]]>
    </line>
    <line>
      <![CDATA[test b running ]]>
    </line>
    <line>
      <![CDATA[test run ofb successful]]>
    </line>
    <line>
      <![CDATA[testing has begun  v]]>
    </line>
    <line>
      <![CDATA[assertion provoded as fail  v]]>
    </line>
    <line>
      <![CDATA[testing has begun  z]]>
    </line>
    <line>
      <![CDATA[test z running ]]>
    </line>
    <line>
      <![CDATA[test run ofz successful]]>
    </line>
    <line>
      <![CDATA[testing has begun  y]]>
    </line>
    <line>
      <![CDATA[test y running ]]>
    </line>
    <line>
      <![CDATA[test run ofy successful]]>
    </line>
  </reporter-output>
  <suite started-at="2024-01-02T20:03:12 IST" name="Suite" finished-at="2024-01-02T20:03:13 IST" duration-ms="107">
    <groups>
    </groups>
    <test started-at="2024-01-02T20:03:12 IST" name="Test" finished-at="2024-01-02T20:03:13 IST" duration-ms="107">
      <class name="testNg.demoTests">
        <test-method signature="a()[pri:0, instance:testNg.demoTests@2f4948e4]" started-at="2024-01-02T20:03:13 IST" name="a" finished-at="2024-01-02T20:03:13 IST" duration-ms="12" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[testing has begun  a]]>
            </line>
            <line>
              <![CDATA[test a running ]]>
            </line>
            <line>
              <![CDATA[test run ofa successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method signature="c()[pri:0, instance:testNg.demoTests@2f4948e4]" started-at="2024-01-02T20:03:13 IST" name="c" finished-at="2024-01-02T20:03:13 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testNg.demoTests.c(demoTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testing has begun  c]]>
            </line>
            <line>
              <![CDATA[assertion provoded as fail  c]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
        <test-method signature="b()[pri:0, instance:testNg.demoTests@2f4948e4]" started-at="2024-01-02T20:03:13 IST" name="b" finished-at="2024-01-02T20:03:13 IST" depends-on-methods="testNg.demoTests.a" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[testing has begun  b]]>
            </line>
            <line>
              <![CDATA[test b running ]]>
            </line>
            <line>
              <![CDATA[test run ofb successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
      </class> <!-- testNg.demoTests -->
      <class name="testNg.Demo2">
        <test-method signature="v()[pri:0, instance:testNg.Demo2@229f66ed]" started-at="2024-01-02T20:03:13 IST" name="v" finished-at="2024-01-02T20:03:13 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testNg.Demo2.v(Demo2.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testing has begun  v]]>
            </line>
            <line>
              <![CDATA[assertion provoded as fail  v]]>
            </line>
          </reporter-output>
        </test-method> <!-- v -->
        <test-method signature="z()[pri:0, instance:testNg.Demo2@229f66ed]" started-at="2024-01-02T20:03:13 IST" name="z" finished-at="2024-01-02T20:03:13 IST" duration-ms="4" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[testing has begun  z]]>
            </line>
            <line>
              <![CDATA[test z running ]]>
            </line>
            <line>
              <![CDATA[test run ofz successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- z -->
        <test-method signature="y()[pri:0, instance:testNg.Demo2@229f66ed]" started-at="2024-01-02T20:03:13 IST" name="y" finished-at="2024-01-02T20:03:13 IST" depends-on-methods="testNg.Demo2.z" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[testing has begun  y]]>
            </line>
            <line>
              <![CDATA[test y running ]]>
            </line>
            <line>
              <![CDATA[test run ofy successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- y -->
      </class> <!-- testNg.Demo2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
